---
version: "1.0"
name: node-info-collector
title: "Node Specification for info collector"
collectors:
  - name: kubeAPIServerSpecFilePermission
    nodeType: master
    audit: stat -c %a /etc/kubernetes/manifests/kube-apiserver.yaml
  - name: kubeAPIServerSpecFileOwnership
    nodeType: master
    audit: stat -c %U:%G /etc/kubernetes/manifests/kube-apiserver.yaml
  - name: kubeControllerManagerSpecFilePermission
    nodeType: master
    audit: stat -c %a /etc/kubernetes/manifests/kube-controller-manager.yaml
  - name: kubeControllerManagerSpecFileOwnership
    nodeType: master
    audit: stat -c %U:%G /etc/kubernetes/manifests/kube-controller-manager.yaml
  - name: kubeSchedulerSpecFilePermission
    nodeType: master
    audit: stat -c %a /etc/kubernetes/manifests/kube-scheduler.yaml
  - name: kubeSchedulerSpecFileOwnership
    nodeType: master
    audit: stat -c %U:%G /etc/kubernetes/manifests/kube-scheduler.yaml
  - name: kubeEtcdSpecFilePermission
    nodeType: master
    audit: stat -c %a /etc/kubernetes/manifests/etcd.yaml
  - name: kubeEtcdSpecFileOwnership
    nodeType: master
    audit: stat -c %U:%G /etc/kubernetes/manifests/etcd.yaml
  - name: KubePKIDirectoryFileOwnership
    nodeType: master
    audit: 'stat -c %U:%G $(ls -R /etc/kubernetes/pki/ | awk ''/:$/&&f{s=$0;f=0}/:$/&&!f{sub(/:$/,"");s=$0;f=1;next}NF&&f{print s"/"$0 }'')'
  - name: KubePKICertificateFilePermissions
    nodeType: master
    audit: 'stat -c %a $(ls -aR /etc/kubernetes/pki/ | awk ''/:$/&&f{s=$0;f=0}/:$/&&!f{sub(/:$/,"");s=$0;f=1;next}NF&&f{print s"/"$0 }''| grep \.crt$)'
  - name: KubePKIKeyFilePermissions
    nodeType: master
    audit: 'stat -c %a $(ls -aR /etc/kubernetes/pki/ | awk ''/:$/&&f{s=$0;f=0}/:$/&&!f{sub(/:$/,"");s=$0;f=1;next}NF&&f{print s"/"$0 }'' | grep \.key$)'''
  - name: kubeletServiceFilePermissions
    nodeType: worker
    audit: stat -c %a /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  - name: kubeletServiceFileOwnership
    nodeType: worker
    audit: stat -c %U:%G /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  - name: kubeletConfFilePermissions
    nodeType: worker
    audit: stat -c %a /etc/kubernetes/kubelet.conf
  - name: kubeletConfFileOwnership
    nodeType: worker
    audit: stat -c %U:%G /etc/kubernetes/kubelet.conf
  - name: kubeletConfigYamlPermission
    nodeType: worker
    audit: stat -c %a /var/lib/kubelet/config.yaml
  - name: kubeletConfigYamlOwnership
    nodeType: worker
    audit: stat -c %U:%G /var/lib/kubelet/config.yaml
  - name: certificateAuthoritiesFilePermissions
    nodeType: worker
    audit: 'stat -c %a $(ps -ef | grep kubelet |grep ''client-ca-file'' | grep -o ''client-ca-file=[^"]\S*'' | awk -F "=" ''{print $2}'' |awk ''FNR <= 1'' 2> /dev/null)'
  - name: certificateAuthoritiesFileOwnership
    nodeType: worker
    audit: 'stat -c %U:%G $(ps -ef | grep kubelet |grep ''client-ca-file'' | grep -o ''client-ca-file=[^"]\S*'' | awk -F "=" ''{print $2}'' |awk ''FNR <= 1'' 2> /dev/null)'
  - name: kubeConfFilePermissions
    nodeType: worker
    audit: 'stat -c %a $(ps -ef | grep kube-proxy |grep ''kubeconfig'' | grep -o ''kubeconfig=[^"]\S* | awk -F "=" ''{print $2}'' |awk ''FNR <= 1'' 2> /dev/null)'
  - name: kubeConfFileOwnership
    nodeType: worker
    audit: 'stat -c %U:%G $(ps -ef | grep kube-proxy |grep ''kubeconfig'' | grep -o ''kubeconfig=[^"]\S* | awk -F "=" ''{print $2}'' |awk ''FNR <= 1'' 2> /dev/null)'



    




    